language: go

go:
  - "1.14"

env: GO111MODULE=on

git:
  depth: 1

sudo: true

install:
  - sudo apt-get install redis

before_script:
  - go test

script:
  - cp db.toml.example db.toml
  - go run .
